apiVersion: v1alpha1
group: management
kind: ExternalSecret
name: gmdemo-webhooksite-axwayid
metadata:
  scope:
    kind: Environment
    name: gmdemo
tags:
  - v1
spec:
  config:
    provider: Kubernetes
    name: ampgw-secret
    namespace: ampgw
  data:
    kind: TLS
    privateKeyAlias: listenerPrivateKey
    certificateAlias: listenerCertificate
---
apiVersion: v1alpha1
group: management
kind: VirtualHost
name: gmdemo-webhooksite-axwayid
metadata:
  scope:
    kind: Environment
    name: gmdemo
tags:
  - v1
spec:
  domain: "webhooksite-axwayid.gmdemo.sandbox.ampc.axwaytest.net"
  secret:
    kind: ExternalSecret
    name: gmdemo-webhooksite-axwayid
---
apiVersion: v1alpha1
group: management
kind: Deployment
name: webhooksite-axwayid
metadata:
  scope:
    kind: Environment
    name: gmdemo
tags:
  - v1
spec:
  virtualAPIRelease: webhooksite-axwayid-1.0.0
  virtualHost: gmdemo-webhooksite-axwayid
