apiVersion: v1alpha1
group: management
kind: VirtualHost
name: nginx
metadata:
  scope:
    kind: Environment
    name: gmdemo
tags:
  - v1
spec:
  domain: "nginx.gmdemo.sandbox.ampc.axwaytest.net"
  secret:
    kind: Secret
    name: ampgw-tls
---
apiVersion: v1alpha1
group: management
kind: Deployment
name: nginx
metadata:
  scope:
    kind: Environment
    name: gmdemo
tags:
  - v1
spec:
  virtualAPIRelease: nginx-1.0.0
  virtualHost: nginx
