apiVersion: v1alpha1
group: management
kind: ExternalSecret
name: resource-vapi-nginx
metadata:
  scope:
    kind: Environment
    name: resource-vapi
tags:
  - v1
spec:
  config:
    provider: Kubernetes
    name: ampgw-secret
    namespace: ampgw
  data:
    kind: TLS
    privateKeyAlias: listenerPrivateKey
    certificateAlias: listenerCertificate
---
apiVersion: v1alpha1
group: management
kind: VirtualHost
name: resource-vapi-nginx
metadata:
  scope:
    kind: Environment
    name: resource-vapi
tags:
  - v1
spec:
  domain: "nginx.resource-vapi.sandbox.ampc.axwaytest.net"
  secret:
    kind: ExternalSecret
    name: resource-vapi-nginx
---
apiVersion: v1alpha1
group: management
kind: Deployment
name: nginx
metadata:
  scope:
    kind: Environment
    name: resource-vapi
tags:
  - v1
spec:
  virtualAPIRelease: nginx-1.0.0
  virtualHost: resource-vapi-nginx
