{
 "title": "Envoy Metrics",
 "tags": [
  "ampgw",
  "envoy"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Active Upstream Connections",
   "type": "stat",
   "gridPos": { "h": 10, "w": 7, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(envoy_cluster_0_0_0_upstream_cx_active) by(envoy_cluster_name)",
     "legendFormat": "{{envoy_cluster_name}}"
    }
   ]
  },
  {
   "title": "Response Time Percentiles",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 17, "x": 7, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(envoy_cluster_0_0_0_upstream_rq_time_bucket[5m])) by (envoy_cluster_name, le))",
     "legendFormat": "50 {{envoy_cluster_name}}"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(envoy_cluster_0_0_0_upstream_rq_time_bucket[5m])) by (envoy_cluster_name, le))",
     "legendFormat": "95 {{envoy_cluster_name}}"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(envoy_cluster_0_0_0_upstream_rq_time_bucket[5m])) by (envoy_cluster_name, le))",
     "legendFormat": "99 {{envoy_cluster_name}}"
    }
   ]
  },
  {
   "title": "Downstream Connection Length",
   "type": "heatmap",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "sum(rate(envoy_listener_downstream_cx_length_ms_bucket[$__rate_interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Total Request Count",
   "type": "timeseries",
   "description": "The cumulative total requests.",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "Requests" } },
   "targets": [
    {
     "expr": "sum(envoy_cluster_0_0_0_internal_upstream_rq_time_count) by (envoy_cluster_name)",
     "legendFormat": "{{envoy_cluster_name}}"
    }
   ]
  },
  {
   "title": "Request Rate",
   "type": "timeseries",
   "description": "The request rate.",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(irate(envoy_cluster_0_0_0_internal_upstream_rq_time_count[$__rate_interval])) by (envoy_cluster_name)",
     "legendFormat": "{{envoy_cluster_name}}"
    }
   ]
  },
  {
   "title": "Upstream Response Rate",
   "type": "timeseries",
   "description": "Response rate by code.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "sum(irate(envoy_cluster_0_0_0_upstream_rq[$__rate_interval])) by (envoy_response_code, envoy_cluster_name)",
     "legendFormat": "{{envoy_response_code}} {{envoy_cluster_name}}"
    }
   ]
  },
  {
   "title": "Listener Connections",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 23 },
   "targets": [
    {
     "expr": "sum(irate(envoy_listener_http_downstream_rq_xx[$__rate_interval])) by (envoy_response_code_class)",
     "legendFormat": "{{envoy_response_code_class}}XX"
    }
   ]
  }
 ]
}