apiVersion: v1alpha1
group: management
kind: ExternalSecret
name: ocdemo-webhooksite
metadata:
  scope:
    kind: Environment
    name: ocdemo
tags:
  - v1
spec:
  config:
    provider: Kubernetes
    name: ampgw-secret
    namespace: ampgw
  data:
    kind: TLS
    privateKeyAlias: listenerPrivateKey
    certificateAlias: listenerCertificate
---
apiVersion: v1alpha1
group: management
kind: VirtualHost
name: ocdemo-webhooksite
metadata:
  scope:
    kind: Environment
    name: ocdemo
tags:
  - v1
spec:
  domain: "webhooksite.ocdemo.sandbox.ampc.axwaytest.net"
  secret:
    kind: ExternalSecret
    name: ocdemo-webhooksite
---
apiVersion: v1alpha1
group: management
kind: Deployment
name: webhooksite
metadata:
  scope:
    kind: Environment
    name: ocdemo
tags:
  - v1
spec:
  virtualAPIRelease: webhooksite-1.0.0
  virtualHost: ocdemo-webhooksite
