apiVersion: v1alpha1
group: management
kind: VirtualAPI
name: webhooksite
spec:
  type: REST
---
group: management
apiVersion: v1alpha1
kind: VirtualService
name: webhooksite
metadata:
  scope:
    kind: VirtualAPI
    name: webhooksite
spec:
  prefix: /hook
  auth:
    kind: PassthroughAuthRule
  route:
    - service:
        prefix: /9f2a136f-7b31-4bae-af5b-14f22448f7e7
        protocol: https
        codec: AUTO
        endpoints:
          - host: webhook.site
            port: 443
      operations:
        - id: getDemo
          path: /demo
          method: GET
