apiVersion: v1alpha1
group: management
kind: VirtualAPI
name: webhooksite
spec:
  type: REST
---
group: management
apiVersion: v1alpha1
kind: VirtualService
name: webhooksite
metadata:
  scope:
    kind: VirtualAPI
    name: webhooksite
spec:
  prefix: /hook
  route:
    - service:
        prefix: /f249ac55-21f7-4f3e-ab29-ab69513aa32c
        protocol: https
        codec: AUTO
        endpoints:
          - host: webhook.site
            port: 443
      operations:
        - id: getDemo
          path: /demo
          method: GET
