apiVersion: v1alpha1
group: management
kind: VirtualAPI
name: webhooksite
spec:
  type: REST
---
group: management
apiVersion: v1alpha1
kind: VirtualService
name: webhooksite
metadata:
  scope:
    kind: VirtualAPI
    name: webhooksite
spec:
  prefix: /hook
  route:
    - service:
        prefix: /ee26a609-ae20-4ccb-aa1d-5577691f56e8
        protocol: https
        codec: AUTO
        endpoints:
          - host: webhook.site
            port: 443
      operations:
        - id: getDemo
          path: /demo
          method: GET
