apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "proxy.fullname" . }}
  labels:
{{ include "proxy.labels" . | indent 4 }}
data:
{{- range $key, $value := .Values.files }}
  {{ $key }}: |-
{{ $value | default "" | indent 4 }}
{{- end -}}
{{- range $key, $value := .Values.templates }}
  {{ $key }}: |-
{{ $valueWithDefault := default "" $value -}}
{{ tpl $valueWithDefault $ | indent 4 }}
{{- end -}}
