apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "proxy.fullname" . }}
  labels:
{{ include "proxy.labels" . | indent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "proxy.selectorLabels" . | nindent 6 }}
  strategy:
    {{ .Values.strategy | nindent 4 }}
  template:
    metadata:
      labels:
        {{- include "proxy.selectorLabels" . | nindent 8 }}
        {{- if .Values.podLabels }}
        ## Custom pod labels
        {{- range $key, $value := .Values.podLabels }}
        {{ $key }}: {{ $value | quote }}
        {{- end }}
        {{- end }}
      annotations:
        checksum/config: {{ include (print .Template.BasePath "/configmap.yaml") . | sha256sum }}
        {{- if .Values.podAnnotations }}
        ## Custom pod annotations
        {{- range $key, $value := .Values.podAnnotations }}
        {{ $key }}: {{ $value | quote }}
        {{- end }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{ toYaml .Values.podSecurityContext | nindent 8 }}
      serviceAccountName: {{ include "proxy.serviceAccountName" . }}
      {{- if .Values.priorityClassName }}
      priorityClassName: "{{ .Values.priorityClassName }}"
      {{- end }}
      terminationGracePeriodSeconds: {{ .Values.terminationGracePeriodSeconds }}
      {{- if .Values.initContainersTemplate }}
      initContainers:
        {{ tpl .Values.initContainersTemplate $ | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            {{ toYaml .Values.command | nindent 12 }}
          args:
            {{- if $.Values.argsTemplate }}
            {{ tpl $.Values.argsTemplate $ | nindent 12}}
            {{- else }}
            {{ toYaml .Values.args | nindent 12 }}
            {{- end }}
          ports:
            {{- with .Values.ports }}
            {{- range $key, $port := . }}
            - name: {{ $key }}
              {{ toYaml $port | nindent 14 }}
            {{- end }}
            {{- end }}
          livenessProbe:
            {{ toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{ toYaml .Values.readinessProbe | nindent 12 }}
          env:
          {{- range $key, $value := .Values.env }}
            - name: {{ $key | upper | replace "." "_" }}
              value: {{ $value | quote }}
          {{- end }}
          resources:
            {{ toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: config
              mountPath: /config
            {{- if .Values.volumeMounts }}
            {{ toYaml .Values.volumeMounts | nindent 12 }}
            {{- end }}
            {{- range $key, $value := .Values.secretMounts }}
            - name: {{ $key }}
              mountPath: {{ $value.mountPath }}
            {{- end }}
          lifecycle:
            {{ toYaml .Values.lifecycle | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{ toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: config
          configMap:
            name: {{ template "proxy.fullname" . }}
        {{- if .Values.volumes }}
        {{ toYaml .Values.volumes | nindent 8 }}
        {{- end }}
        {{- range $key, $value := .Values.secretMounts }}
        - name: {{ $key }}
          secret:
            secretName: {{ $value.secretName }}
            defaultMode: {{ $value.defaultMode }}
        {{- end }}
