apiVersion: v1alpha1
group: management
kind: ExternalSecret
name: ocdemo-jsonplaceholder
metadata:
  scope:
    kind: Environment
    name: ocdemo
tags:
  - v1
spec:
  config:
    provider: Kubernetes
    name: ampgw-secret
    namespace: ampgw
  data:
    kind: TLS
    privateKeyAlias: listenerPrivateKey
    certificateAlias: listenerCertificate
---
apiVersion: v1alpha1
group: management
kind: VirtualHost
name: ocdemo-jsonplaceholder
metadata:
  scope:
    kind: Environment
    name: ocdemo
tags:
  - v1
spec:
  domain: "jsonplaceholder.ocdemo.sandbox.ampc.axwaytest.net"
  secret:
    kind: ExternalSecret
    name: ocdemo-jsonplaceholder
---
apiVersion: v1alpha1
group: management
kind: Deployment
name: jsonplaceholder
metadata:
  scope:
    kind: Environment
    name: ocdemo
tags:
  - v1
spec:
  virtualAPIRelease: jsonplaceholder-1.0.0
  virtualHost: ocdemo-jsonplaceholder
