apiVersion: v1alpha1
group: management
kind: VirtualAPI
name: jsonplaceholder
spec:
  type: REST
---
group: management
apiVersion: v1alpha1
kind: VirtualService
name: jsonplaceholder
metadata:
  scope:
    kind: VirtualAPI
    name: jsonplaceholder
spec:
  prefix: /json
  auth:
    kind: PassthroughAuthRule
  route:
    - service:
        prefix: /
        protocol: https
        codec: AUTO
        endpoints:
          - host: jsonplaceholder.typicode.com
            port: 443
      operations:
        - id: getTodo
          path: /todos/{id}
          method: GET
        - id: getTodos
          path: /todos
          method: GET